baseurl = "https://www.pricewell.io"
languageCode = "en-us"
title = "Stripe subscription payments with No Code"
disableKinds = ["taxonomy", "taxonomyTerm", "term"]
theme = "pricewell"
[params]
    description = "Start charging for your subscription based service with embeddable pricing pages from PriceWell. Built on top of Stripe, our no code pricing pages let you start billing your customers instantly."
[markup.goldmark.renderer]
unsafe= true
[build]
 writeStats = true