name: Publish Site

on:
    push:
        branches:
            - main

jobs:
    build-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@main

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: '0.79.0'

            - name: Clean public directory
              run: rm -rf public

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '12.x'

            - name: Cache dependencies
              uses: actions/cache@v1
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: npm install
              run: npm ci

            - name: Build
              run: hugo --gc --minify

            - name: Create cname file
              run: echo 'www.pricewell.io' > public/CNAME

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
